/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.da.bao.bei

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project

import spock.lang.Specification

/**
 * A simple unit test for the '\com.da.bao.bei.greeting' plugin.
 */
class DabaobeiPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.da.bao.bei.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
