/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.da.bao.bei

import com.android.build.gradle.AppExtension
import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class DabaobeiPlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
//        project.tasks.register("greeting") {
//            doLast {
//                println("Hello from plugin 'com.da.bao.bei.greeting'")
//            }
//        }

//        project.android.applicationVariants.each { variant ->
//            variant.outputs.all {
//                println("${variant.name}-${variant.versionName}.apk")
//                outputFileName = "${variant.name}-${variant.versionName}.apk"
//            }
//        }

        AppExtension appExtension = project.extensions.findByType(AppExtension.class)
        appExtension.registerTransform(new MyTransform())
    }
}
